name: "Setup OTP & Elixir, Get Deps, Compile, Run Tests"
on:
  workflow_call:
    inputs:
      checkout:
        description: "Whether to check out the code. Set to `false` to disable this, e.g. if you have already done this."
        type: boolean
      warnings-as-errors:
        description: "Whether warning during compilation should be shown as errors and mark the workflow as failed."
        type: boolean
        default: true
      with-kubernetes:
        description: "Whether to setup a Kubernetes cluster with Kind."
        type: boolean
      include-integration-tests:
        description: "Whether to run include tests in test run."
        type: boolean
        default: false
      compile-for:
        description: "What env to compile the app for (defaults to test)."
        type: string
        default: test
      mix-test-timeout:
        description: "Sets the timeout on the mix test call (ms)."
        type: number
        default: 60000
      extra_excludes:
        description: |
          Additional matrix exclusions in YAML format, e.g.:
            - elixir: "1.15"
              otp: "23"
            - elixir: "1.16"
              otp: "23"
        type: string
        required: false
        default: ""
    secrets:
      token:
        description: "The github token"
        required: true
env:
  MIX_ENV: test
  # renovate: datasource=docker depName=kindest/node
  KUBERNETES_NODE_VERSION: v1.35.1@sha256:05d7bcdefbda08b4e038f644c4df690cdac3fba8b06f8289f30e10026720a1ab
  KUBECONFIG: /home/runner/.kube/config
  MISE_ENV: ci
  GITHUB_TOKEN: ${{ secrets.token }}
jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    env:
      BASE_EXCLUDES: |
        # OTP 24
        - elixir: "1.17"
          otp: "24"
        - elixir: "1.18"
          otp: "24"
        - elixir: "1.19"
          otp: "24"
        # OTP 25
        - elixir: "1.19"
          otp: "25"
        # OTP 27
        - elixir: "1.15"
          otp: "27"
        - elixir: "1.16"
          otp: "27"
        # OTP 28
        - elixir: "1.15"
          otp: "28"
        - elixir: "1.16"
          otp: "28"
        - elixir: "1.17"
          otp: "28"
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - id: build
        env:
          EXTRA_EXCLUDES: ${{ inputs.extra_excludes }}
        run: |
          if [ -z "$EXTRA_EXCLUDES" ]; then
            MERGED=$(echo "$BASE_EXCLUDES" | yq -o=json)
          else
            MERGED=$(yq eval-all '. as $item ireduce([]; . + $item)' \
              <(echo "$BASE_EXCLUDES") \
              <(echo "$EXTRA_EXCLUDES") \
              | yq -o=json)
          fi

          echo "matrix=$(echo "{}" | yq ".exclude = $MERGED" -o=json)" >> $GITHUB_OUTPUT

  elixir-test:
    runs-on: ubuntu-latest
    name: Test - OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        # See https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        otp: ["24", "25", "26", "27", "28"]
        elixir: ["1.15", "1.16", "1.17", "1.18", "1.19"]
        exclude: ${{ fromJSON(needs.prepare_matrix.outputs.matrix).exclude }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        if: inputs.checkout != false

      - name: Setup Mise JDX
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          echo "eval \"\$(mise activate bash)\"" >> ~/.bash_profile
          mise install erlang elixir
          echo "otp-version=$(mise current erlang | tr -d '\n')" >> "$GITHUB_OUTPUT"
          echo "elixir-version=$(mise current elixir | tr -d '\n')" >> "$GITHUB_OUTPUT"

      - name: Setup Kubernetes (Kind)
        if: inputs.with-kubernetes == true
        id: kind
        run: |
          mise x kind -- kind create cluster --image kindest/node:$KUBERNETES_NODE_VERSION

      - name: Retrieve Build Cache
        uses: actions/cache@v5
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ steps.mise.outputs.otp-version }}-${{ steps.mise.outputs.elixir-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v5
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.mise.outputs.otp-version }}-${{ steps.mise.outputs.elixir-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Hex
        run: mise x elixir@${{ steps.mise.outputs.elixir-version }} erlang@${{ steps.mise.outputs.otp-version }} rebar -- mix local.hex --force

      - name: Install Mix Dependencies
        run: mise x elixir@${{ steps.mise.outputs.elixir-version }} erlang@${{ steps.mise.outputs.otp-version }} rebar -- mix deps.get

      - name: Compile Application / Library
        run: mise x elixir@${{ steps.mise.outputs.elixir-version }} erlang@${{ steps.mise.outputs.otp-version }} rebar -- mix compile --warnings-as-errors
        if: inputs.warnings-as-errors == true
        env:
          MIX_ENV: ${{ inputs.compile-for }}

      - name: Compile Application / Library
        run: mise x elixir@${{ steps.mise.outputs.elixir-version }} erlang@${{ steps.mise.outputs.otp-version }} rebar -- mix compile
        if: inputs.warnings-as-errors != true
        env:
          MIX_ENV: ${{ inputs.compile-for }}

      - name: Run Tests
        if: inputs.include-integration-tests != true
        shell: bash -l {0}
        run: mise x elixir@${{ steps.mise.outputs.elixir-version }} erlang@${{ steps.mise.outputs.otp-version }} rebar -- mix test --timeout ${{ inputs.mix-test-timeout }}

      - name: Run Tests incl. integration tests
        if: inputs.include-integration-tests == true
        shell: bash -l {0}
        run: mise x elixir@${{ steps.mise.outputs.elixir-version }} erlang@${{ steps.mise.outputs.otp-version }} rebar -- mix test --include integration --timeout ${{ inputs.mix-test-timeout }}
